// GENERATED BY HAND FOR BARÈNG; FOLLOW firebase_config instructions in AGENTS.md
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported for this build.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        // Android-first project; other platforms intentionally not configured yet.
        throw UnsupportedError(
          'FirebaseOptions have not been configured for this platform. Android is primary.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5pcyHyPlrSRaX90n4dxGtkX52NFYge6E',
    appId: '1:405330435328:android:e542998a6a4149c91fe7e5',
    messagingSenderId: '405330435328',
    projectId: 'bareng-b9d88',
    databaseURL: 'https://bareng-b9d88-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bareng-b9d88.firebasestorage.app',
  );
}
